
export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED"
export const POST_FAVORITE = 'POST_FAVORITE';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

export const JOBLISTS_LOADING = "JOBLISTS_LOADING";
export const JOBLISTS_FAILED = "JOBLISTS_FAILED";
export const ADD_JOBLISTS = "ADD_JOBLISTS";








